### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by fansariadeh** [xpuoxford/L2G-neurips2021#2]
It is mentioned that data/ is a folder for datasets but it is not available in the repository. Can you please upload the dataset you have used?

**Comment by xpuoxford** [comment]
The folder [data/] is to store the simulation datasets after you run [data_simulation.py] by yourself. The datasets are simulated. We didn't keep the datasets because they eat much memory and it is not necessary. However, we did include the source code for simulation. Please check the paper and code.
